export const CONSTANTS = Object.freeze({
  SERVER_NAME_LOCAL: 'local',
  SERVER_NAME_DEV: 'dev',
  HTTP_STATUS_BAD_REQUEST_CODE: 400,
  HTTP_STATUS_BAD_REQUEST_MESSAGE: 'Bad Request',
  PREFECTURE_LIST_COMPONENT_NAME: 'WPrefectureList',
  CITY_LIST_COMPONENT_NAME: 'WCityList',
  SEARCH_BOX_COMPONENT_NAME: 'WSearchBox',
  HOSPITAL_LIST_COMPONENT_NAME: 'WHospitalList',
  SUBJECT_LIST_COMPONENT_NAME: 'WSubjectList',
  SELECT_COMPONENT_NAME: 'WSelect',
  HIDDEN_COMPONENT_NAME: 'WHidden',
  DATE_TIME_LOCAL_COMPONENT_NAME: 'WDatetimeLocal',
  SELECT_RANGE_COMPONENT_NAME: 'WSelectRange',
  LABEL_COMPONENT_NAME: 'WLabel',
  NATIVE_LINK_COMPONENT_NAME: 'WNativeLink',
  REDIRECT_LINK_COMPONENT_NAME: 'WRedirectLink',
  FORMAT_DATA_COMPONENT_NAME: 'WFormatData',
  BUTTON_LINK_COMPONENT_NAME: 'WButtonLink',
  BUTTON_COMPONENT_NAME: 'WButton',
  BUTTON_NEXT_COMPONENT_NAME: 'WButtonNext',
  BUTTON_PREV_COMPONENT_NAME: 'WButtonBack',
  BUTTON_CONFIRMATION_COMPONENT_NAME: 'WButtonConfirm',
  CHECKBOX_COMPONENT_NAME: 'WCheckbox',
  INDICATOR_COMPONENT_NAME: 'WIndicator',
  SWITCH_COMPONENT_NAME: 'WSwitch',
  CHECKBOX_GROUP_COMPONENT_NAME: 'WCheckboxGroup',
  TEXT_COMPONENT_NAME: 'WText',
  RADIO_GROUP_COMPONENT_NAME: 'WRadioGroup',
  RADIO_ICON_COMPONENT_NAME: 'WRadioIcon',
  DATE_PICKER_COMPONENT_NAME: 'WDatepicker',
  TEXT_AREA_COMPONENT_NAME: 'WTextarea',
  LINE_CHART_COMPONENT_NAME: 'WLineChart',
  RECORDING_CALENDAR_GRID_COMPONENT_NAME: 'WRecordingCalendar',
  CHECKBOX_ICON_COMPONENT_NAME: 'WCheckboxIcon',
  HOSPITAL_VISIT: 'hospitalVisit',
  PREFECTURE_CODE: 'prefecture_code',
  REQUIRED: 'required',
  MAX_COUNT: 'max_count',
  COUNT_OVER_ONE: 'count_over_1',
  SUBMIT: 'submit',
  BUTTON: 'button',
  GONEXT: 'button_next',
  GOBACK: 'button_back',
  CLEAR: 'clear',
  SPECIAL: 'special',
  STRING: 'string',
  NUMBER: 'number',
  BOOLEAN: 'bool',
  ARRAY: 'array',
  FLOAT: 'float',
  ARRAY_OF_STRING: 'array_of_string',
  INTEGER: 'integer',
  BOLD: 'bold',
  ROWS: 'rows',
  NORMAL: 'normal',
  FONT_SIZE: 'font-size',
  FONT_COLOR: 'font-color',
  BACKGROUND_COLOR: 'background-color',
  CHECK_COLOR: 'checked-color',
  BORDER_COLOR: 'border-color',
  UNCHECKED_COLOR: 'unchecked-color',
  ERROR_HIGHLIGHT: 'error-highlight',
  INDICATOR_COLOR: 'indicator-color',
  INDICATOR_POINTER_COLOR: 'indicator-pointer-color',
  HIDDEN_TYPE: 'hidden',
  HIDDEN_CITY_ID: '0000_hidden_city_id',
  HIDDEN_CITY_STRING: '_hidden_city_id',
  HIDDEN_DCF_FACILITY_ID: '0000_hidden_dcf_facility_id',
  HIDDEN_DCF_FACILITY_STRING: '_hidden_dcf_facility_id',
  HIDDEN_DCF_FACILITY_CODE: '0000_hidden_dcf_facility_code',
  HIDDEN_DCF_FACILITY_CODE_STRING: '_hidden_dcf_facility_code',
  GO_TO_ANOTHER_HOSPITAL_GROUP: '_go_another_hospital_group',
  SYMPTOMS_TOTAL_HEALTH_ID: '0000_total_health',
  HIDDEN_PREF_CD_ID: '0000_hidden_pref_cd',
  HIDDEN_PREF_CD_STRING: '_hidden_pref_cd',
  HIDDEN_SUBJECT_ID: '0000_hidden_subject_id',
  HIDDEN_SUBJECT_STRING: '_hidden_subject_id',
  PROFILE_CONTENT: 'profile__content',
  DOCTOR_STRING: '_doctor',
  PHONE_STRING: '_phoneno',
  CURRENT_DISEASE_RADIO_STRING: '_current_disease_radio',
  DISEASE_GROUP_CD_STRING: '_disease_group_cd',
  DISEASE_GROUP_UC_STRING: '_disease_group_uc',
  NOTIFY_BUTTON_STRING: '_is_notify_button',
  NEXT_VISIT_DATE_STRING: '_next_visit_date',
  NEXT_VISIT_TIME_STRING: '_next_visit_time',
  GUIDE_POSITION_STRING: '_guide_position',
  HOSPITAL_NAME_STRING: '_hospital_name',
  GREED_WEEK_STRING: '_grid_week',
  VALIDATION_STRING_LENGTH: 'string_length',
  VALIDATION_DIGIT_DECIMAL_COUNT_X_Y: 'digit_decimal_count_x_y',
  VALIDATION_DATE_TODAY_OR_AFTER: 'date_today_or_after',
  VALIDATION_DATE_TODAY_OR_BEFORE: 'date_today_or_before',
  VALIDATION_DIGIT_COUNT_UPTO_X: 'digit_count_upto_x',
  VALIDATION_NUMBER_ONLY: 'number_only',
  VALIDATION_DECIMAL_ONLY: 'number_decimal_only',
  VALIDATION_COUNT_OVER_ONE: 'count_over_1',
  IS_EMPTY_VALUE: ['-1', null, '', ' ', undefined],
  CITY_LABEL_STRING: '_city_label',
  PREFECTURE_LABEL_STRING: '_prefecture_label',
  HOSPITAL_NAME_LABEL_STRING: '_hospital_name_label',
  SUBJECTS_LABEL_STRING: '_subjects_label',
  DOCTOR_LABEL_STRING: '_doctor_label',
  PHONE_NO_LABEL_STRING: '_phoneno_label',
  DEFECATION_GROUP_STRING: '_defecation_group',
  BIRTHDAY_LABEL_STRING: '_birthday_label',
  DATE_FORMAT: 'date',
  TIME_PICKER_COMPONENT_NAME: 'WTimepicker',
  NUMBER_COMPONENT_NAME: 'WNumber',
  LABEL_STYLE: 'label_style',
  LABEL_REQUIRED_STYLE: 'label_required_style',
  PX_NEEDED_KEYS: ['font-size'],
  LABEL: 'label',
  LABEL_REQUIRED: 'label-required',
  SYMPTOMS_SCREEN_CODE: '0400',
  SYMPTOMS_SCREEN_CODE2: '0411',
  DATE_STATIC_TIME_FORMAT: 'YYYY-MM-DD_00-00-00',
  DYNAMIC_DATE_TIME_FORMAT: 'YYYY-MM-DD_HH-MM-SS',
  DYNAMIC_DATE_TIME_LOCAL_FORMAT: 'YYYY-MM-DDTHH:mm:ss',
  WCSMTP1001_API: 'WCSMTP1001',
  WCSMTP1003_API: 'WCSMTP1003',
  WCUP1002_API: 'WCUP1002',
  WCUP1001_API: 'WCUP1001',
  WCMI1001_API: 'WCMI1001',
  WCRTSP1001_API: 'WCRTSP1001',
  WCNHV1001_API: 'WCNHV1001',
  WCMI1002_API: 'WCMI1002',
  WCSMTP1002_API: 'WCSMTP1002',
  INDICATOR_BODY_PARTS_COMPONENT_NAME: 'WIndicatorBodyParts',
  PAIN_PARTS_BACK_STRING: '_pain_parts_back_',
  PAIN_PARTS_FRONT_STRING: '_pain_parts_front_',
  PAIN_PARTS_FRONT_ABDOMEN: '_pain_parts_front_abdomen',
  PAIN_PARTS_FRONT_CHEST: '_pain_parts_front_chest',
  PAIN_PARTS_FRONT_HEAD: '_pain_parts_front_head',
  PAIN_PARTS_FRONT_LEFT_ARM: '_pain_parts_front_left_arm',
  PAIN_PARTS_FRONT_LEFT_LEG: '_pain_parts_front_left_leg',
  PAIN_PARTS_FRONT_RIGHT_ARM: '_pain_parts_front_right_arm',
  PAIN_PARTS_FRONT_RIGHT_LEG: '_pain_parts_front_right_leg',
  PAIN_PARTS_FRONT_WHOLE_BODY: '_pain_parts_front_whole_body',
  PAIN_PARTS_BACK_WAIST: '_pain_parts_back_waist',
  PAIN_PARTS_BACK_BACK: '_pain_parts_back_back',
  PAIN_PARTS_BACK_HEAD: '_pain_parts_back_head',
  PAIN_PARTS_BACK_LEFT_ARM: '_pain_parts_back_left_arm',
  PAIN_PARTS_BACK_LEFT_LEG: '_pain_parts_back_left_leg',
  PAIN_PARTS_BACK_RIGHT_ARM: '_pain_parts_back_right_arm',
  PAIN_PARTS_BACK_RIGHT_LEG: '_pain_parts_back_right_leg',
  PAIN_PARTS_BACK_WHOLE_BODY: '_pain_parts_back_whole_body',
  ANSWERED_STRING: '_answered',
  SYMPTOMS_MODEL_ID: '_slider',
  HEAD: '頭部',
  LEFT_HAND: '左腕',
  IRREGULAR_PULSE_WAVE: '不規則脈波（IHB）',
  LEFT_LEG: '左足',
  RIGHT_HAND: '右腕',
  RIGHT_LEG: '右足',
  WAIST: '腰',
  WHOLE_BODY: '全身',
  ABDOMEN: '腹部',
  CHEST: '胸',
  PAIN: '痛み',
  TAKING_MEDICINE: '服薬',
  STOMACH_ACHE: '腹痛',
  BACK_HEAD: '後頭部',
  FRONT_HEAD: '前頭部',
  ANTI_DIARRHEAL: '下痢止め',
  BLOODY_STOOL: '血便',
  MEMO: 'メモ',
  LUNCH: '昼食',
  DINNER: '夕食',
  BREAKFAST: '朝食',
  PART_BACK: '背中',
})

export const sharedProps = {
  errorMessagesColor: {
    type: String,
    default: '#ff0000',
  },
  contentBackgroundColor: {
    type: String,
    default: 'white',
  },
  contentFontWeight: {
    type: String,
    default: '400',
  },
  contentFontSize: {
    type: String,
    default: '16px',
  },
  contentTextColor: {
    type: String,
    default: 'black',
  },
  labelRequiredBold: {
    type: String,
    default: '600',
  },
  labelRequiredFontSize: {
    type: String,
    default: '12px',
  },
  labelRequiredFontColor: {
    type: String,
    default: 'red',
  },
  labelRequiredBackgroundColor: {
    type: String,
    default: 'white',
  },
  labelBold: {
    type: String,
    default: 'normal',
  },
  labelFontSize: {
    type: String,
    default: '16px',
  },
  labelFontColor: {
    type: String,
    default: 'black',
  },
  labelBackgroundColor: {
    type: String,
    default: 'red',
  },
  componentReturnType: {
    type: String,
    default: null,
  },
}
export const shapeKeyMap = [
  {
    type: '▲',
    key: 'triangle',
  },
  {
    type: '△',
    key: 'triangle',
  },
  {
    type: '●',
    key: 'circle',
  },
  {
    type: '◎',
    key: 'circle',
  },
  {
    type: '○',
    key: 'circle',
  },
  {
    type: '◆',
    key: 'rectRot ',
  },
  {
    type: '◇',
    key: 'rectRot ',
  },
  {
    type: '■',
    key: 'rect ',
  },
  {
    type: '□',
    key: 'rect ',
  },
]
